### PR TITLE
replace unlink with rm

### PR DESCRIPTION
**Pull request by felabr**

### CODE REVIEW

**Comment by felabr** [comment]
sorry, that should have gone to my fork, and not to your repo

**Comment by nonara** [comment]
Np. @felabr If I may ask, why did you need to swap it?

**Comment by felabr** [comment]
Sure, there's some information in this discussion: https://github.com/nonara/ts-patch/discussions/164

Our GitHub pipelines sometimes fail when running ts-patch, and the error message tells me `unlinkSync` cannot find the lock file. Yes, I've seen the `existsSync`. Anyway, `rmSync` has this nice `force` option that would make it ignore missing files.

**Comment by nonara** [comment]
Thanks for sharing! Seems reasonable to consider this.

I'll need to check support on node versions and make sure there are no potential downsides. Will reopen for now

**Comment by felabr** [comment]
I cleaned it up a bit, the PR now only contains the `unlinkSync` / `rmSync` change.

**Pull request merged**
